#
#
#
#
#

FILES	=	usropt.rtf releases.rtf nordauto.rtf xmasgift.rtf
TEXTS	=	usropt.txt releases.txt nordauto.txt xmasgift.txt


_default:
	@echo "$(MAKE): specify something to make!"
	@sh -c ' exit -1 '

all:	$(FILES)

texts:	$(TEXTS)


#Portable Apps, formerly "NORD /usr/opt"
usropt.rtf:
	#wget -O $FID.$FMT $URL/export?format=$FMT
	wget -O usropt.rtf \
 https://docs.google.com/a/casita.net/document/d/1QBsK--hq6qHOBpKCMQYln4qck39xfi7s1FTL73G-7VM/export?format=rtf
usropt.txt:
	wget -O usropt.txt \
 https://docs.google.com/a/casita.net/document/d/1QBsK--hq6qHOBpKCMQYln4qck39xfi7s1FTL73G-7VM/export?format=txt

#NORD-releases
releases.rtf:
	wget -O releases.rtf \
 https://docs.google.com/a/casita.net/document/d/1Q3b6oAx2QL310FozVFI9qRRRJmZhOC_KawTay9nbpZ4/export?format=rtf
releases.txt:
	wget -O releases.txt \
 https://docs.google.com/a/casita.net/document/d/1Q3b6oAx2QL310FozVFI9qRRRJmZhOC_KawTay9nbpZ4/export?format=txt

#NORDAUTO
nordauto.rtf:
	wget -O nordauto.rtf \
 https://docs.google.com/a/casita.net/document/d/1QQQ4xV51lZkisQEK307B4A1AvU_YtG6eNd7QazQCnFs/export?format=rtf
nordauto.txt:
	wget -O nordauto.txt \
 https://docs.google.com/a/casita.net/document/d/1QQQ4xV51lZkisQEK307B4A1AvU_YtG6eNd7QazQCnFs/export?format=txt

#MEMO XMASGIFT
xmasgift.rtf:
	wget -O xmasgift.rtf \
 https://docs.google.com/a/casita.net/document/d/10zc4Z8VrwTBEcQK1L1G9n2J6jMakUEQs_uUNB9G11U8/export?format=rtf
xmasgift.txt:
	wget -O xmasgift.txt \
 https://docs.google.com/a/casita.net/document/d/10zc4Z8VrwTBEcQK1L1G9n2J6jMakUEQs_uUNB9G11U8/export?format=txt

#NORD Source Trust
srctrust.rtf:
	wget -O srctrust.rtf \
 https://docs.google.com/document/d/11AaYxnPO0Ej8Gd_HtW4Ru320rsPEcKfex2oDoRCcFkA/export?format=rtf
srctrust.txt:
	wget -O srctrust.txt \
 https://docs.google.com/document/d/11AaYxnPO0Ej8Gd_HtW4Ru320rsPEcKfex2oDoRCcFkA/export?format=txt

#NORD Linux -or- NORD Scratch Linux
#https://docs.google.com/a/casita.net/document/d/1QQyCdRe4oHvxFv_23u1DX1rO7EVzhreB6zC3OoCPycM

#NORD Overview
#https://docs.google.com/a/casita.net/document/d/1mwIMqmf1f2xd3pTHeCw7vhaodxECZizus2js9gt95H4


clean:
	@rm -f $(FILES)


# parent
#https://drive.google.com/folderview?id=0B7AkQhEvbQZfMmVkMzIwMDctM2EyMi00MzBhLWIzYTktOGYyY2EzNGFiYzg3

#NORD
#https://drive.google.com/a/casita.net/#folders/0B7AkQhEvbQZfMmVkMzIwMDctM2EyMi00MzBhLWIzYTktOGYyY2EzNGFiYzg3

# etc
#https://drive.google.com/folderview?id=0B7AkQhEvbQZfNWIwMmQ1NTktMjZmMS00Mjg1LTk3NGYtZWVlMDFmYmVlM2Ri


