#!/bin/sh
#
#
#         Name: /etc/init.d/cmsfsrun (shell INIT script)
#               run a profiling shell script from CMS minidisk via INIT
#      Pre-req: 'cmsfscat' from the CMS FS Utility suite
#               This script attempts to read the file without mounting the disk.
#
#

#
# simplistic announcement that we are running
echo "$0 $*" > /dev/console

#
# the name of the file on the CMS 191 disk which we are after
CMSFSRUN_FILE=profile.sh
CMSFSRUN_DISK=191
CMSFSRUN_TEMP=/dev/shm/cmsfs
# can be changed in /etc/sysconfig/cmsfsrun

### BEGIN INIT INFO
# Provides:             cmsfsrun
# Required-Start:       network
# Required-Stop:
# Default-Start:          1 2 3 4 5
# Default-Stop:         0           6
# Short-Description:    run a profile from CMS minidisk
# Description:
### END INIT INFO

#
# are we running on System Z or s390 or s390x? all others N/A
CHCCWDEV=`which chccwdev 2> /dev/null`
if [ -z "$CHCCWDEV" ] ; then exit ; fi

#
# if there is a config file then source it now
if [ -r /etc/sysconfig/cmsfsrun ] ; then
      . /etc/sysconfig/cmsfsrun ; fi

#
# the following case block renders this a viable INIT script
# (except that we really should follow LSB better w/r/t the comments)
# (which we hope to do ... soon ... real soon ... yep)
case $1 in

  start)
    # fall through
    :
    ;;

  stop)
    # nothing to do
    exit
    ;;

  restart|reload|force_reload)
    $0 stop
    $0 start
    exit
    ;;

  status)
    # nothing to do
    exit
    ;;

  *)
    echo "Usage: $0 {start|stop}" 1>&2
    exit 3
    ;;

esac

#
# retrieve the block device name of the 191 disk
D191=`grep "^0\.0\.0$CMSFSRUN_DISK" /proc/dasd/devices \
  | awk -F ')' '{print $3}' | awk '{print $2}'`
# if it is not listed then try to vary the 191 disk online
if [ -z "$D191" ] ; then
  D191R=OFF
#  echo "+ chccwdev -e $CMSFSRUN_DISK"
          chccwdev -e $CMSFSRUN_DISK 1> /dev/null 2> /dev/null
# try again to get the device name from the kernel
  D191=`grep "^0\.0\.0$CMSFSRUN_DISK" /proc/dasd/devices \
    | awk -F ')' '{print $3}' | awk '{print $2}'`
fi
# if it still does not show up then exit silently
if [ -z "$D191" ] ; then exit ; fi

#
# conditionally create block device files
tail -n +3 /proc/partitions \
  | awk '{print "mknod -m 660 /dev/" $4 " b " $1 " " $2}' 2> /dev/null \
  | sh 2> /dev/null

#
# read the file of interest from CMS space
mkdir -p -m 700 $CMSFSRUN_TEMP
cmsfscat -d /dev/$D191 -a $CMSFSRUN_FILE 1> $CMSFSRUN_TEMP/$CMSFSRUN_FILE 2> /dev/null
RC=$?

#
# if the read was successful and the file is not empty then run it
if [ "$RC" -eq 0 -a -s $CMSFSRUN_TEMP/$CMSFSRUN_FILE ] ; then
  chmod +x $CMSFSRUN_TEMP/$CMSFSRUN_FILE
  $CMSFSRUN_TEMP/$CMSFSRUN_FILE ; RC=$?
else RC=0 ; fi

#
# if the 191 disk was offline when we started then restore that state
if [ "$D191R" = OFF ] ; then
#  echo "+ chccwdev -d $CMSFSRUN_DISK"
          chccwdev -d $CMSFSRUN_DISK 1> /dev/null 2> /dev/null
fi

#
# clean up after ourselves
rm -r $CMSFSRUN_TEMP

exit $RC


