#!/bin/sh
#
#
#         Name: /etc/init.d/named (shell INIT script)
#	  Date: 2004-Mar-26 (Fri)
#		2010-Sep-19 (Sun)
#		2016-Jun-11 (Sat)
#
#

### BEGIN INIT INFO
# Provides:             named
# Required-Start:       network
# Required-Stop:
# Default-Start:          1 2 3 4 5
# Default-Stop:         0           6
# Short-Description:    start and stop the DNS server
# Description:          start and stop the DNS server
### END INIT INFO

D=/tmp ; cd /tmp
if [ -d /var/named ] ; then D=/var/named ; cd /var/named ; fi

echo "$0 $*" > /dev/console

if [ -d /usr/opt/bind/bin ] ; then PATH=/usr/opt/bind/bin:$PATH ; fi
if [ -d /usr/opt/bind/sbin ] ; then PATH=/usr/opt/bind/sbin:$PATH ; fi

case "$1" in

  start|restart)
    if [ -s /var/run/named.pid ] ; then
      cat /var/run/named.pid | xargs -n 1 kill ; fi
    sync ; sync ; sleep 1
    named -c /etc/named.conf -g \
	1> /var/log/named.1 2> /var/log/named.2 & # -u named -g named
    ;;

  stop)
    if [ -s /var/run/named.pid ] ; then
      cat /var/run/named.pid | xargs -n 1 kill ; fi
    sync ; sync ; sleep 3
    if [ -s /var/run/named.pid ] ; then
      cat /dev/null > /var/run/named.pid ; fi
    ;;

  start_msg)
    echo "DNS server starting"
    ;;

  stop_msg)
    echo "DNS server stopping"
    ;;

  restart|reload|force_reload)
    $0 stop
    $0 start
    exit
    ;;

  stat*)
    # nothing to do
    exit
    ;;

  *)
    echo "Usage: $0 {start|stop}" 1>&2
    exit 3
    ;;

esac


